version: '3.8'

services:
  app:
    build: .
    container_name: biblioteca
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/opt/jboss/wildfly/standalone/log
    environment:
      HOST: db
      NAME: poowTrab
      USER: postgres
      PASS: 1234
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: poowTrab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
